version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE_NAME=bobby
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DIALECT=mysql
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bobby
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
